name: CI
on: pull_request


jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build sosw docs
      run:  sudo apt-get install python3-sphinx; pwd; ls; pip install boto3 sphinx-sitemap sphinx_rtd_theme; sphinx-build -ab html ./docs ./sosw-rtd