name: CI
on: pull_request

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Call sosw_docs_builder ApiGateway
      run: curl -X POST  https://sn4n6wyvj1.execute-api.us-west-2.amazonaws.com/dev
